repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3
-   repo: https://github.com/pycqa/flake8.git
    rev: 3.7.7
    hooks:
    -   id: flake8
        language: python_venv
