name: earthpy-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytest
  - pytest-vcr

  # System management
  - keyring
  - platformdirs

  # Web
  - requests
  
  # Core scientific python
  - numpy
  - matplotlib

  # Geo stuff
  - geopandas
  - rasterio
  - scikit-image