name: earthpy-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytest
  - pytest-vcr

  # System management
  - keyring
  - platformdirs

  # Data management
  - dvc
  - humanize

  # Web
  - requests
  
  # Core scientific python
  - numpy
  - matplotlib

  # Geo stuff
  - geopandas
  - rasterio
  - scikit-image