# This workflow  runs tests for earthpy
# Because we want a conda environment -  and that builds  slower,
# we divided up  tests from linting and docs  to make  for simpler  install envts

name: Run Tests - Matrix OS / Python Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runtests:
    name: conda (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.10'
            environment-file: ci/py310-env.yml
            coverage: true
          - os: ubuntu-latest
            python-version: '3.11'
            environment-file: ci/py311.yml
            coverage: false
          - os: ubuntu-latest
            python-version: '3.12'
            environment-file: ci/py312.yml
            coverage: false
          - os: macos-latest
            python-version: '3.12'
            environment-file: ci/py312.yml
            coverage: false
          - os: windows-latest
            python-version: '3.12'
            environment-file: ci/py312.yml
            coverage: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          channels: conda-forge
          channel-priority: true
          auto-update-conda: false
          auto-activate-base: false
          environment-file: ${{ matrix.environment-file }}
          activate-environment: earthpy-dev
      - name: Show environment
        run: conda list
      - name: Run fast tests
        if: ${{ !matrix.coverage }}
        run: pytest -v --color=yes -m "not slow"
      - name: Run fast tests with coverage
        if: ${{ matrix.coverage }}
        run: pytest -v --color=yes -m "not slow" --cov=earthpy --cov-report=xml
      - name: Upload coverage to Codecov
        if: ${{ matrix.coverage && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
